version: '3'
services:
  backend-java:
    build:
      context: ./backend-java
    ports:
      - '8082:8082'
    restart: always
    environment:
      - Qiniu-AccessKey=${Qiniu-AccessKey}
      - Qiniu-SecretKey=${Qiniu-SecretKey}
      - Qiniu-BucketName=${Qiniu-BucketName}
    depends_on:
      - mysql8
  backend-go:
    image: jaronnie/admin-backend-go:latest
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      - mysql8
  fronted:
    build:
      context: ./fronted
    ports:
      - '8080:80'
  oracle11g:
    image: deepdiver/docker-oracle-xe-11g
    restart: always
    container_name: backend-oracle11g
    ports:
      - '1521:1521'
  dameng8:
    image: dm8_single:dm8_20230808_rev197096_x86_rh6_64
    restart: always
    container_name: backend-dameng8
    privileged: true
    environment:
      - PAGE_SIZE=16
      - LD_LIBRARY_PATH=/opt/dmdbms/bin
      - EXTENT_SIZE=32
      - BLANK_PAD_MODE=1
      - LOG_SIZE=1024
      - UNICODE_FLAG=1
      - LENGTH_IN_CHAR=1
      - INSTANCE_NAME=backend-dameng8
    volumes:
      - ./deploy/dameng8/data:/opt/dmdbms/data
    ports:
      - '30236:5236'
  mysql8:
    image: mysql:8.0.32
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    restart: always
    container_name: backend-mysql8
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
    volumes:
      - ./deploy/mysql8/data:/var/lib/mysql
      - ./deploy/mysql8/config:/etc/mysql/conf.d
      - ./deploy/mysql8/sql:/docker-entrypoint-initdb.d
