version: '3'
services:
  stdb:
    image: jaronnie/ragingcd-stdb:latest
    restart: always
    environment:
      - Qiniu_AccessKey=${Qiniu_AccessKey}
      - Qiniu_SecretKey=${Qiniu_SecretKey}
      - Qiniu_BucketName=${Qiniu_BucketName}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mysql8
  core:
    image: jaronnie/ragingcd-core:latest
    restart: always
    depends_on:
      - mysql8
  fronted:
    image: jaronnie/ragingcd-fronted:latest
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - stdb      
  # oracle11g:
  #   image: deepdiver/docker-oracle-xe-11g
  #   restart: always
  #   container_name: ragingcd-oracle11g
  # dameng8:
  #   image: dm8_single:dm8_20230808_rev197096_x86_rh6_64
  #   restart: always
  #   container_name: ragingcd-dameng8
  #   privileged: true
  #   environment:
  #     - PAGE_SIZE=16
  #     - LD_LIBRARY_PATH=/opt/dmdbms/bin
  #     - EXTENT_SIZE=32
  #     - BLANK_PAD_MODE=1
  #     - LOG_SIZE=1024
  #     - UNICODE_FLAG=1
  #     - LENGTH_IN_CHAR=1
  #     - INSTANCE_NAME=ragingcd-dameng8
  #   volumes:
  #     - ./deploy/dameng8/data:/opt/dmdbms/data
  mysql8:
    image: mysql:8.0.32
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    restart: always
    container_name: ragingcd-mysql8
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
    volumes:
      - ./deploy/mysql8/data:/var/lib/mysql
      - ./deploy/mysql8/config:/etc/mysql/conf.d
      - ./deploy/mysql8/sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:5.0
    container_name: ragingcd-redis
    restart: always
    volumes:
      - ./deploy/redis/data:/data
    ports:
      - '6379:6379'
