version: '3'
services:
  gateway:
    # The official v2 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "28080:8080"
    labels: 
      - "traefik.http.middlewares.prefix-stripper.stripprefixregex.regex=/apps.*?/"
      - "traefik.http.middlewares.auth-middleware.forwardauth.address=http://stdb:8082/api/v1.0/system/user/auth" # 鉴权中间件调用 stdb 的 auth 接口
      - "traefik.http.middlewares.auth-middleware.forwardauth.authresponseheaders=X-Forward-Auth-Header" # 鉴权中间件自定义的响应头部
      - "traefik.http.middlewares.auth-middleware.forwardauth.trustForwardHeader=true"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock   
  stdb:
    image: jaronnie/ragingcd-stdb:latest
    restart: always
    labels:
      - "traefik.http.routers.stdb.rule=PathPrefix(`/apps.stdb`)"
      - "traefik.http.routers.stdb.middlewares=prefix-stripper"      
    environment:
      - Qiniu_AccessKey=${Qiniu_AccessKey}
      - Qiniu_SecretKey=${Qiniu_SecretKey}
      - Qiniu_BucketName=${Qiniu_BucketName}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mysql8
  core:
    image: jaronnie/ragingcd-core:latest
    restart: always
    labels:
      - "traefik.http.routers.core.rule=PathPrefix(`/apps.core`)"
      - "traefik.http.routers.core.middlewares=prefix-stripper, auth-middleware"    
    depends_on:
      - mysql8
  fronted:
    image: jaronnie/ragingcd-fronted:latest
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - stdb      
  mysql8:
    image: mysql:8.0.32
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    restart: always
    container_name: ragingcd-mysql8
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
    volumes:
      - ./deploy/mysql8/data:/var/lib/mysql
      - ./deploy/mysql8/config:/etc/mysql/conf.d
      - ./deploy/mysql8/sql:/docker-entrypoint-initdb.d
  redis:
    image: redis:5.0
    container_name: ragingcd-redis
    restart: always
    volumes:
      - ./deploy/redis/data:/data