version: "3"

tasks:
  build:fronted:
    cmds:
      - cd fronted;pnpm i;pnpm run build;cd ..
    silent: true
  build:core:
    cmds:
      - cd core;GOOS=linux GOARCH=amd64 go build;cd ..
    silent: true
  build:stdb:
    cmds:
      - cd stdb;mvn package -Dmaven.test.skip=true;cd ..
    silent: true    
  docker:build:fronted:
    deps:
      - build:fronted
    cmds:
      - cd fronted;docker build -t jaronnie/ragingcd-fronted:latest .;cd ..
    silent: true
  docker:build:core:
    deps:
      - build:core
    cmds:
      - cd core;docker build -t jaronnie/ragingcd-core:latest .;cd ..
    silent: true
  docker:build:stdb:
    deps:
      - build:stdb
    cmds:
      - cd stdb;docker build -t jaronnie/ragingcd-stdb:latest .;cd ..
    silent: true    
  docker:push:fronted:
    deps:
      - docker:build:fronted
    cmds:
      - docker push jaronnie/ragingcd-fronted:latest     
  docker:push:core:
    deps:
      - docker:build:core
    cmds:
      - docker push jaronnie/ragingcd-core:latest
  docker:push:stdb:
    deps:
      - docker:build:stdb
    cmds:
      - docker push jaronnie/ragingcd-stdb:latest
  deploy:production:
    cmds:
      - docker-compose -f docker-compose-production.yaml up -d
  deploy:dev:
    deps:
      - build:fronted
      - build:stdb
      - build:core
    cmds:
      - docker-compose -f docker-compose-dev.yaml up -d --build