version: "3"

tasks:
  build:fronted:
    cmds:
      - cd fronted;pnpm i;pnpm run build;cd ..
    silent: true
  build:backend-go:
    cmds:
      - cd backend-go;GOOS=linux GOARCH=amd64 go build;cd ..
    silent: true
  build:backend-java:
    cmds:
      - cd stdb;mvn package -Dmaven.test.skip=true;cd ..
    silent: true    
  docker:build:fronted:
    deps:
      - build:fronted
    cmds:
      - cd fronted;docker build -t jaronnie/admin-fronted:latest .;cd ..
    silent: true
  docker:build:backend-go:
    deps:
      - build:backend-go
    cmds:
      - cd backend-go;docker build -t jaronnie/admin-backend-go:latest .;cd ..
    silent: true
  docker:build:backend-java:
    deps:
      - build:backend-java
    cmds:
      - cd backend-java;docker build -t jaronnie/admin-backend-java:latest .;cd ..
    silent: true    
  docker:push:fronted:
    deps:
      - docker:build:fronted
    cmds:
      - docker push jaronnie/admin-fronted:latest     
  docker:push:backend-go:
    deps:
      - docker:build:backend-go
    cmds:
      - docker push jaronnie/admin-backend-go:latest
  docker:push:backend-java:
    deps:
      - docker:build:backend-java
    cmds:
      - docker push jaronnie/admin-backend-java:latest