name: Deploy-fronted

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy-fronted.yml'    
      - 'Taskfile.yml'
      - 'fronted/**'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.2"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.ACCESS_TOKEN }}          

      - name: build src and docker build image and push to docker hub
        run: |
          npm i -g pnpm@8.0.0
          task docker:push:fronted

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker pull jaronnie/admin-fronted
            cd ragingcd
            docker-compose stop fronted
            docker-compose up -d fronted