name: Deploy-core

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Taskfile.yml'    
      - 'core/**'
      - '.github/workflows/deploy-core.yml'      

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.6'

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.ACCESS_TOKEN }}

      - name: build src and docker build image and push to docker hub
        run: |
          task docker:push:core

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker pull jaronnie/ragingcd-core
            cd ragingcd
            docker-compose stop core
            docker-compose up -d core